### PR TITLE
ETL pipeline enhancements and bug fixes

### PR DESCRIPTION
**Pull request by aybanda**
@bellanov 
# ETL Pipeline Enhancements and Bug Fixes

## Changes

1. Fixed `extract_api_data()` function:
   - Removed unnecessary argument causing TypeError
   - Ensured correct calling within `extract()` function

2. Implemented environment variable for API URL:
   - Added `python-dotenv` for loading environment variables
   - Replaced hardcoded API_URL with `os.getenv('API_URL', 'https://api.example.com/data')`
   - Enhanced security and flexibility of API URL management

3. Updated `.gitignore`:
   - Added `.env` to prevent committing sensitive information

4. Improved `main.py`:
   - Simplified error handling in `extract_api_data()`
   - Added check in `extract()` to return dummy data if API data is None
   - Removed duplicate `ThreadPoolExecutor` in `extract()` function

6. Modified `test_main.py`:
   - Adjusted test cases to align with current `main.py` implementation

## Testing

- Updated unit tests to reflect new function names and behavior
- Ensured all tests pass with the new changes

Screenshot 2024-09-07 at 8 33 46 AM

Screenshot 2024-09-07 at 8 34 20 AM

## Next Steps

- Conduct thorough testing of the ETL pipeline with various data scenarios
- Consider adding more comprehensive error handling and logging
- Explore opportunities for further performance optimizations

## Notes

These changes improve the code's functionality, security, and flexibility. The main issues addressed were the TypeError in `extract_api_data()` and making the API URL configurable through environment variables.

### CODE REVIEW

**Comment by bellanov** [comment]
You must really want that bike lol. Great turn around time. 

Reviewing. Seems it's time to isolate and get it into its own formal build pipeline.

Pipelines imply remote execution, so we have the foundations of one, but we're still executing locally.

All the build pipeline would do is the same thing we're doing locally... just away from our machines.

From there, we build artifacts, tag them, and then post releases. 

This is a good release description so if recommend getting to formal releases instead of leaving these descriptions in PRs.

From there, we can put it on our resumes and say released x blah blah times.

**Comment by aybanda** [comment]
You know I'm not serious about bike though right ;) , but yes keen on collecting bounties. 
 You're absolutely right. Moving to a formal build pipeline is a great next step for your project. It will help with consistency, automation, and scalability. Here's a high-level overview of how you might approach this:
1. Containerisation 
2. CI/CD Configuration
3. Remote Execution
4. Artifact Building
5. Versioning and Tagging
6. Release management

**Review by bellanov — COMMENTED** [review]
Glad you said that. Been there done that with regards to CICD. Time to throw ideas up. Got some ideas for some industry-breaking tools that aren't too difficult to pursue.

Here is an example of a **Continuous Integration (CI)** Pipeline triggered by tag that is attached to a merge request to GCP.

I updated the **python-template** project up to _3.12_. A build _**(Version 1.9.0)**_ and its status is attached to the Pull Request.

**Pull Request:**
https://github.com/bellanov/python-template/pull/17

**Build Details:**
https://github.com/bellanov/python-template/pull/17/checks?check_run_id=29823777359

I'll create a template project to house these change appropriately, namely **etl-pipeline** or something. This will be tagged, versioned, and have managed releases, etc.

The build output in **Google Cloud Platform (GCP)**.

image

**Review by bellanov — APPROVED** [review]

**Comment by bellanov** [comment]
Thanks again, let me get to delivering that bounty.

**Pull request closed without merging**
